/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <cstdint>
#include <iostream>
using namespace std;

// ==============================
// 🔹 Register Addresses
// ==============================
constexpr std::uint32_t RCC_AHB1ENR_ADDR = 0x40023830;
constexpr std::uint32_t GPIOD_MODER_ADDR = 0x40020C00;
constexpr std::uint32_t GPIOD_ODR_ADDR   = 0x40020C14;

constexpr uint32_t GPIOA_MODER_ADDR = 0x40020000;
constexpr uint32_t GPIOA_IDR_ADDR   = 0x40020010;

// ==============================
// 🔹 Register Access
// ==============================
inline volatile std::uint32_t& RCC_AHB1ENR =
    *reinterpret_cast<volatile std::uint32_t*>(RCC_AHB1ENR_ADDR);

inline volatile std::uint32_t& GPIOD_MODER =
    *reinterpret_cast<volatile std::uint32_t*>(GPIOD_MODER_ADDR);

inline volatile std::uint32_t& GPIOD_ODR =
    *reinterpret_cast<volatile std::uint32_t*>(GPIOD_ODR_ADDR);

inline volatile uint32_t& GPIOA_MODER = *reinterpret_cast<volatile uint32_t*>(GPIOA_MODER_ADDR);
inline volatile uint32_t& GPIOA_IDR   = *reinterpret_cast<volatile uint32_t*>(GPIOA_IDR_ADDR);


// ==============================
// 🔹 Step 1: Low-level driver (explicit)
// ==============================
class GPIO
{
public:
    static void enable_clock()
    {
        RCC_AHB1ENR |= (1U << 3);  // Enable GPIOD clock
        RCC_AHB1ENR |= (1U << 0);
    }

    static void set_output(std::uint32_t pin)
    {
        GPIOD_MODER &= ~(3U << (pin * 2));
        GPIOD_MODER |=  (1U << (pin * 2));
    }

    static void toggle(std::uint32_t pin)
    {
        GPIOD_ODR ^= (1U << pin);
    }
    static void set_input(uint32_t pin)
    {
    	GPIOA_MODER &=~(3U<<(pin*2));
    }
    static int read()
    {
    	return (GPIOA_IDR&1);
    }
};

// ==============================
// 🔹 Step 2: High-level abstraction (constructor)
// ==============================
class LED
{
    std::uint32_t led_pin;
    uint32_t sw_pin;

public:
    explicit LED(std::uint32_t p,uint32_t p1) : led_pin(p),sw_pin(p1)
    {
        // Assumes clock is already enabled
        GPIO::set_output(led_pin);
        GPIO::set_input(sw_pin);
    }

    void toggle()
    {
        GPIO::toggle(led_pin);
    }
    int status()
    {
    	return GPIO::read();
    }
};

// ==============================
// 🔹 Delay function
// ==============================
void delay()
{
    for (volatile std::uint32_t i = 0; i < 100000; ++i)
    {
        // Prevent optimization
    }
}

// ==============================
// 🔹 Step 3: Controlled initialization in main()
// ==============================
int main()
{
    constexpr std::uint32_t LED_PIN = 12;
    constexpr uint32_t led1=13;
    constexpr uint32_t SW_PIN = 0;
    // Explicit hardware initialization
    GPIO::enable_clock();
    GPIO::set_output(led1);
    // Safe object creation (after hardware is ready)
    LED led(LED_PIN,SW_PIN);

    while (true)
    {
    	if(led.status())
    	{
        led.toggle();
        delay();
    	}
    	else
    	{
    		GPIO::toggle(led1);
    		delay();
    	}
    }
}
