/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
/*
#include <stdio.h>
#include <cstdint>
#include "stm32f407.h"
void gpio_init()
{
	RCC->AHB1ENR|=(1<<0);
	RCC->AHB1ENR|=(1<<0);
	GPIOA->MODER&=~(3<<0);
	GPIOD->MODER&=~(3<<24);
	GPIOD->MODER |=(1<<24);
}
uint8_t read_pin()
{
	return ((GPIOA->IDR>>0)&1);
}
void fun()
{
	printf("PORT A0 SWITCH PRESSED");
	GPIOD->ODR^=(1<<12);
	for (volatile int i = 0; i < 100000; i++);
}
int main(void)
{
	gpio_init();
    printf("Hello World\n");
	//for(;;);

    while(1)
    {
    	if(read_pin())
    	{
    		fun();
    	}

    	 for (volatile int i = 0; i < 100000; i++);
    }
}
*/

#include <stdio.h>
#include <stdint.h>  // Use stdint.h for C files
#include "stm32f407.h"

void gpio_init(void)
{
    // Enable Clocks: Bit 0 = Port A, Bit 3 = Port D
    RCC->AHB1ENR |= (1 << 0) | (1 << 3);

    // Configure PA0 as Input (Bits 1:0 = 00)
    GPIOA->MODER &= ~(3 << 0);

    // Configure PD12 as Output (Bits 25:24 = 01)
    GPIOD->MODER &= ~(3 << 24);
    GPIOD->MODER |=  (1 << 24);
}

uint8_t read_pin(void)
{
    // Mask bit 0 of the Input Data Register
    return (uint8_t)((GPIOA->IDR >> 0) & 1);
}

void fun(void)
{
    // Note: Added \n for proper line buffering in consoles
    printf("PORT A0 SWITCH PRESSED\n");
    GPIOD->ODR ^= (1 << 12); // Toggle Green LED
    for (volatile int i = 0; i < 500000; i++); // Short debounce/visible delay
}

int main(void)
{
    gpio_init();
    printf("Hello World\n");

    while(1)
    {
        if(read_pin())
        {
            fun();
        }
        // General loop delay to prevent CPU saturation
        for (volatile int i = 0; i < 100000; i++);
    }
}
