/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <iostream>
using namespace std;

template<uint32_t address>
struct Register
{
	static volatile uint32_t& value()
	{
		return *reinterpret_cast<volatile uint32_t*>(address);
	}
};

constexpr uint32_t RCC_AHB1ENR_ADDR = 0x40023830;
constexpr uint32_t GPIOD_MODER_ADDR = 0x40020C00;
constexpr uint32_t GPIOD_ODR_ADDR   = 0x40020C14;

constexpr uint32_t GPIOA_MODER_ADDR = 0x40020000;
constexpr uint32_t GPIOA_IDR_ADDR   = 0x40020010;


class GPIO
{
public:
	static void clock_enable()noexcept
	{
		Register<RCC_AHB1ENR_ADDR>::value() |=(1U<<3);
		Register<RCC_AHB1ENR_ADDR>::value() |=(1U<<0);
	}
	static void set_OUTPUT(uint32_t pin)noexcept
	{
		auto& moder=Register<GPIOD_MODER_ADDR>::value();

		moder&=~(3U<<(pin*2));
		moder|=(1U<<(pin*2));
	}
	static void set_INPUT(uint32_t pin)noexcept
	{
		Register<GPIOA_MODER_ADDR>::value()&=~(3U<<(pin*2));
	}
	static void Toggle(uint32_t pin)noexcept
	{
		Register<GPIOD_ODR_ADDR>::value()^=(1U<<pin);
	}
	static void Led_ON(uint32_t pin)noexcept
	{
		Register<GPIOD_ODR_ADDR>::value()|=(1U<<pin);
	}
	static void Led_OFF(uint32_t pin)noexcept
	{
		Register<GPIOD_ODR_ADDR>::value()&=~(1U<<pin);
	}
	static int Read_Status()noexcept
	{
		auto& r=Register<GPIOA_IDR_ADDR>::value();
		return ((r>>0)&1);
	}
};

void delay()
{
	for(volatile uint32_t i=0;i<100000;i++)
	{

	}
}

int main()
{
	constexpr uint32_t LED_PIN = 12;
	constexpr uint32_t LED_p   = 13;
	constexpr uint32_t Switch_PIN = 0;

	GPIO::clock_enable();

	GPIO::set_INPUT(Switch_PIN);

	GPIO::set_OUTPUT(LED_PIN);
	GPIO::set_OUTPUT(LED_p);

	while(true)
	{
		uint8_t st = GPIO::Read_Status();

		if(st)
		{
			GPIO::Toggle(LED_PIN);
			GPIO::Led_OFF(LED_p);
			delay();
		}
		else
		{
			GPIO::Led_ON(LED_p);
			delay();
		}
	}
}











